# Generated by Django 3.0.7 on 2020-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='site_url',
            field=models.CharField(max_length=1000),
        ),
    ]
